name: 'PageUp Code Scanning Action'
author: "PageUp"
description: "Execute code analysis"
inputs:
  solutionFilePath: 
    description: 'File path of solution'
    required: true
runs:
  using: "composite"
  steps:
    - run: dotnet tool install --global security-scan
      shell: bash
    - run: dotnet build ${{ inputs.solutionFilePath }}
      shell: bash
    - run: security-scan ${{ inputs.solutionFilePath }} --export=out.sarif
      shell: bash
    - run: cat out.sarif
      shell: bash
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: out.sarif
#     - name: Add Coverage PR Comment
#       uses: marocchino/sticky-pull-request-comment@v2
#       if: github.event_name == 'pull_request'
#       with:
#         recreate: true
#         path: code-coverage-results.md
