name: 'PageUp Code Scanning Action'
author: "PageUp"
description: "Execute code analysis"
runs:
  using: "composite"
  steps:
    - run: dotnet tool install --global security-scan
      shell: bash
    - run: dotnet tool install --global dotnet-script
      shell: bash
    - run: find . -name "*.sln" -exec dotnet build {} \;
      shell: bash
    - run: find . -name "*.sln" -exec security-scan {} --export={}.sarif \;
      shell: bash
    - run: curl https://raw.githubusercontent.com/PageUpPeopleOrg/pageup-codescanning-action/main/sarif-to-markdown.csx -o ./sarif-to-markdown.csx
      shell: bash
    - run: dotnet script ./sarif-to-markdown.csx
      shell: bash
    - run: pwd
      shell: bash
    - run: find . -name "*.sarif"
      shell: bash
    - run: ls -l
      shell: bash
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        hide_and_recreate: true
        path: "./code-coverage-results.md"
