name: 'PageUp Code Scanning Action'
author: "PageUp"
description: "Execute code analysis"
inputs:
  solutionFilePath: 
    description: 'File path of solution'
    required: true
runs:
  using: "composite"
  steps:
    - run: dotnet tool install --global security-scan
      shell: bash
    - run: dotnet build ${{ inputs.solutionFilePath }}
      shell: bash
    - run: security-scan ${{ inputs.solutionFilePath }} --export=out.sarif
      shell: bash
    - run: cat out.sarif
      shell: bash
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.2.0
      with:
        filename: out.sarif
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
