name: 'PageUp Code Scanning Action'
author: "PageUp"
description: "Execute code analysis"
inputs:
  solutionFilePath: 
    description: 'File path of solution'
    required: true
runs:
  using: "composite"
  steps:
    - run: dotnet tool install --global security-scan
      shell: bash
    - run: dotnet build ${{ inputs.solutionFilePath }}
      shell: bash
    - run: security-scan ${{ inputs.solutionFilePath }}
      shell: bash
