name: 'PageUp Code Scanning Action'
author: "PageUp"
description: "Execute code analysis"
runs:
  using: "composite"
  steps:
    - name: 🛠️ Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          6.0.x
          8.0.x
    - run: dotnet tool install --global security-scan
      shell: bash
    - run: dotnet tool install --global dotnet-script --version 1.3.1
      shell: bash
    - run: find . -name "*.sln" -exec dotnet build {} /p:ErrorLog="ErrorLog.sarif%2Cversion=2.1" \;
      shell: bash
    - run: find . -name "*.sln" -exec security-scan {} --export={}.sarif \;
      shell: bash
    - run: curl https://raw.githubusercontent.com/PageUpPeopleOrg/pageup-codescanning-action/main/sarif-to-markdown.csx -o ./sarif-to-markdown.csx
      shell: bash
    - run: dotnet script ./sarif-to-markdown.csx
      shell: bash
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        hide_and_recreate: true
        path: ./code-coverage-results.md
